import './Process.css'
import Search from '../../assets/Search.svg'
import Select from '../../assets/Select.svg'
import Standout from '../../assets/Standout.svg'


export function Process() {
    return (
        <div className="process-outer">
            <div className="process-inner">
                <section className="single-item">
                    <img src={Search} alt="search" className="search-img" />
                    <h1 className="item-heading">Search</h1>
                    <p className="item-text">
                        Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.
                    </p>

                </section>
                <section className="single-item">
                    <img src={Select} alt="search" className="search-img" />
                    <h1 className="item-heading">Select</h1>
                    <p className="item-text">
                        Choose from thousands of options generated by the slogan maker that fit your needs.
                    </p>

                </section>
                <section className="single-item">
                    <img src={Standout} alt="search" className="search-img" />
                    <h1 className="item-heading">Standout</h1>
                    <p className="item-text">
                        Congrats on your new slogan. It's time to win the world!
                    </p>

                </section>

            </div>
        </div>

    )
}